


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: telusko-api1
          uri: lb://TELUSKOAPP1
          predicates:
            - Path=/info
        - id: telusko-api2
          uri: lb://TELUSKOAPP2
          predicates:
            - Path=/moreinfo
         
  application:
    name: msh-5m6-api-gateway

server:
  port: 4444   